/*------------------------------------------------------------------------------

	Lucena Build Abstraction Library
	“Generated.hpp”
	Copyright © 2019 Lucena
	All Rights Reserved

	This file is distributed under the University of Illinois Open Source
	License. See license/License.txt for details.

	This file is automatically generated by the build system.

------------------------------------------------------------------------------*/


#pragma once


#define LBAL_version_major 2
#define LBAL_version_minor 0
#define LBAL_version_patch 0
