/*------------------------------------------------------------------------------

	Lucena Build Abstraction Library
	“lbalTest”
	Copyright © 2015-2020 Lucena
	All Rights Reserved

	This file is distributed under the University of Illinois Open Source
	License. See license/License.txt for details.

------------------------------------------------------------------------------*/


//	std
#include <iostream>


//	gtest
#include <gtest/gtest.h>


//	lbal
#include <lucenaBAL/lucenaBAL.hpp>


/*------------------------------------------------------------------------------
	Declarations
*/



#define LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING 0
#define LBAL_DIAGNOSTIC_LOG_ALL_STATUS 1
#define LBAL_DIAGNOSTIC_LOG_ALL_UNSUPPORTED 1

#if LBAL_DIAGNOSTIC_LOG_ALL_STATUS
	#define LBAL_DIAGNOSTIC_LOG_SUPPORTED(LBAL_DIAGNOSTIC_feature_) \
		std::cerr << LBAL_DIAGNOSTIC_feature_ " is supported" << std::endl;
#elif
	#define LBAL_DIAGNOSTIC_LOG_SUPPORTED(LBAL_DIAGNOSTIC_feature_)
#endif

#if LBAL_LOG_DIAGNOSTIC_ALL_STATUS || LBAL_DIAGNOSTIC_LOG_ALL_UNSUPPORTED
	#define LBAL_DIAGNOSTIC_LOG_UNSUPPORTED(LBAL_DIAGNOSTIC_feature_) \
		std::cerr << LBAL_DIAGNOSTIC_feature_ " is UNSUPPORTED" << std::endl;
#elif
	#define LBAL_DIAGNOSTIC_LOG_UNSUPPORTED(LBAL_DIAGNOSTIC_feature_)
#endif

//	__FIXME__ This only works in C++17 or later, being a holdover from before
//	the more inclusive rewrite.
#define LBAL_DIAGNOSTIC_TEST(LBAL_DIAGNOSTIC_feature_) \
	do { \
		if constexpr (0 == LBAL_DIAGNOSTIC_feature_) { \
			LBAL_DIAGNOSTIC_LOG_UNSUPPORTED (#LBAL_DIAGNOSTIC_feature_) \
		} else { \
			LBAL_DIAGNOSTIC_LOG_SUPPORTED (#LBAL_DIAGNOSTIC_feature_) \
		} \
	} while (false)


using namespace LBAL_;


/*------------------------------------------------------------------------------
*/

GTEST_TEST (lbalTest, Validation)
{
	/*	Report the results of the various feature tests. In addition to
		runtime reporting, there is also compile-time reporting; depending on
		your IDE, you may not even need to explicitly compile to see the test
		results.

		__SEEME__ Note that we can’t use preprocessor or template magic when
		displaying warning messages, so gratuitous boilerplate is needed.
	*/

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP98_EXCEPTIONS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP98_EXCEPTIONS
		LBAL_CPP_WARNING ("LBAL_CPP98_EXCEPTIONS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP98_RTTI);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP98_RTTI
		LBAL_CPP_WARNING ("LBAL_CPP98_RTTI is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_ALIAS_TEMPLATES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_ALIAS_TEMPLATES
		LBAL_CPP_WARNING ("LBAL_CPP11_ALIAS_TEMPLATES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_ATTRIBUTE_CARRIES_DEPENDENCY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_ATTRIBUTE_CARRIES_DEPENDENCY
		LBAL_CPP_WARNING ("LBAL_CPP11_ATTRIBUTE_CARRIES_DEPENDENCY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_ATTRIBUTE_NORETURN);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_ATTRIBUTE_NORETURN
		LBAL_CPP_WARNING ("LBAL_CPP11_ATTRIBUTE_NORETURN is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_ATTRIBUTES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_ATTRIBUTES
		LBAL_CPP_WARNING ("LBAL_CPP11_ATTRIBUTES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_CONSTEXPR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_CONSTEXPR
		LBAL_CPP_WARNING ("LBAL_CPP11_CONSTEXPR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_DECLTYPE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_DECLTYPE
		LBAL_CPP_WARNING ("LBAL_CPP11_DECLTYPE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_DELEGATING_CONSTRUCTORS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_DELEGATING_CONSTRUCTORS
		LBAL_CPP_WARNING ("LBAL_CPP11_DELEGATING_CONSTRUCTORS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_INHERITING_CONSTRUCTORS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_INHERITING_CONSTRUCTORS
		LBAL_CPP_WARNING ("LBAL_CPP11_INHERITING_CONSTRUCTORS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_INITIALIZER_LISTS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_INITIALIZER_LISTS
		LBAL_CPP_WARNING ("LBAL_CPP11_INITIALIZER_LISTS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_LAMBDAS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_LAMBDAS
		LBAL_CPP_WARNING ("LBAL_CPP11_LAMBDAS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_MINIMAL_GARBAGE_COLLECTION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_MINIMAL_GARBAGE_COLLECTION
		LBAL_CPP_WARNING ("LBAL_CPP11_MINIMAL_GARBAGE_COLLECTION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_NSDMI);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_NSDMI
		LBAL_CPP_WARNING ("LBAL_CPP11_NSDMI is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_RANGE_BASED_FOR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_RANGE_BASED_FOR
		LBAL_CPP_WARNING ("LBAL_CPP11_RANGE_BASED_FOR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_RAW_STRINGS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_RAW_STRINGS
		LBAL_CPP_WARNING ("LBAL_CPP11_RAW_STRINGS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_REF_QUALIFIERS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_REF_QUALIFIERS
		LBAL_CPP_WARNING ("LBAL_CPP11_REF_QUALIFIERS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_RVALUE_REFERENCES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_RVALUE_REFERENCES
		LBAL_CPP_WARNING ("LBAL_CPP11_RVALUE_REFERENCES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_STATIC_ASSERT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_STATIC_ASSERT
		LBAL_CPP_WARNING ("LBAL_CPP11_STATIC_ASSERT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_THREADSAFE_STATIC_INIT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_THREADSAFE_STATIC_INIT
		LBAL_CPP_WARNING ("LBAL_CPP11_THREADSAFE_STATIC_INIT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_UNICODE_CHARACTERS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_UNICODE_CHARACTERS
		LBAL_CPP_WARNING ("LBAL_CPP11_UNICODE_CHARACTERS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_UNICODE_LITERALS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_UNICODE_LITERALS
		LBAL_CPP_WARNING ("LBAL_CPP11_UNICODE_LITERALS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_USER_DEFINED_LITERALS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_USER_DEFINED_LITERALS
		LBAL_CPP_WARNING ("LBAL_CPP11_USER_DEFINED_LITERALS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_VARIADIC_TEMPLATES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP11_VARIADIC_TEMPLATES
		LBAL_CPP_WARNING ("LBAL_CPP11_VARIADIC_TEMPLATES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_AGGREGATE_NSDMI);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP14_AGGREGATE_NSDMI
		LBAL_CPP_WARNING ("LBAL_CPP14_AGGREGATE_NSDMI is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_ATTRIBUTE_DEPRECATED);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP14_ATTRIBUTE_DEPRECATED
		LBAL_CPP_WARNING ("LBAL_CPP14_ATTRIBUTE_DEPRECATED is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_BINARY_LITERALS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP14_BINARY_LITERALS
		LBAL_CPP_WARNING ("LBAL_CPP14_BINARY_LITERALS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_CONSTEXPR_RELAXED_CONSTRAINTS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP14_CONSTEXPR_RELAXED_CONSTRAINTS
		LBAL_CPP_WARNING ("LBAL_CPP14_CONSTEXPR_RELAXED_CONSTRAINTS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_DECLTYPE_AUTO);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP14_DECLTYPE_AUTO
		LBAL_CPP_WARNING ("LBAL_CPP14_DECLTYPE_AUTO is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_GENERIC_LAMBDAS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP14_GENERIC_LAMBDAS
		LBAL_CPP_WARNING ("LBAL_CPP14_GENERIC_LAMBDAS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_INIT_CAPTURES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP14_INIT_CAPTURES
		LBAL_CPP_WARNING ("LBAL_CPP14_INIT_CAPTURES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_RETURN_TYPE_DEDUCTION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP14_RETURN_TYPE_DEDUCTION
		LBAL_CPP_WARNING ("LBAL_CPP14_RETURN_TYPE_DEDUCTION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_SIZED_DEALLOCATION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP14_SIZED_DEALLOCATION
		LBAL_CPP_WARNING ("LBAL_CPP14_SIZED_DEALLOCATION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_VARIABLE_TEMPLATES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP14_VARIABLE_TEMPLATES
		LBAL_CPP_WARNING ("LBAL_CPP14_VARIABLE_TEMPLATES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_AGGREGATE_BASES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_AGGREGATE_BASES
		LBAL_CPP_WARNING ("LBAL_CPP17_AGGREGATE_BASES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_ALIGNED_NEW);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_ALIGNED_NEW
		LBAL_CPP_WARNING ("LBAL_CPP17_ALIGNED_NEW is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_ATTRIBUTE_FALLTHROUGH);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_ATTRIBUTE_FALLTHROUGH
		LBAL_CPP_WARNING ("LBAL_CPP17_ATTRIBUTE_FALLTHROUGH is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_ATTRIBUTE_MAYBE_UNUSED);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_ATTRIBUTE_MAYBE_UNUSED
		LBAL_CPP_WARNING ("LBAL_CPP17_ATTRIBUTE_MAYBE_UNUSED is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_ATTRIBUTE_NODISCARD);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_ATTRIBUTE_NODISCARD
		LBAL_CPP_WARNING ("LBAL_CPP17_ATTRIBUTE_NODISCARD is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_CAPTURE_STAR_THIS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_CAPTURE_STAR_THIS
		LBAL_CPP_WARNING ("LBAL_CPP17_CAPTURE_STAR_THIS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_CONSTEXPR_LAMBDA);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_CONSTEXPR_LAMBDA
		LBAL_CPP_WARNING ("LBAL_CPP17_CONSTEXPR_LAMBDA is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_DEDUCTION_GUIDES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_DEDUCTION_GUIDES
		LBAL_CPP_WARNING ("LBAL_CPP17_DEDUCTION_GUIDES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_DEDUCTION_GUIDES_DR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_DEDUCTION_GUIDES_DR
		LBAL_CPP_WARNING ("LBAL_CPP17_DEDUCTION_GUIDES_DR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_DEDUCTION_GUIDES_NB);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_DEDUCTION_GUIDES_NB
		LBAL_CPP_WARNING ("LBAL_CPP17_DEDUCTION_GUIDES_NB is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_ENUMERATOR_ATTRIBUTES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_ENUMERATOR_ATTRIBUTES
		LBAL_CPP_WARNING ("LBAL_CPP17_ENUMERATOR_ATTRIBUTES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_FOLD_EXPRESSIONS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_FOLD_EXPRESSIONS
		LBAL_CPP_WARNING ("LBAL_CPP17_FOLD_EXPRESSIONS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_FOLD_EXPRESSIONS_REVISED);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_FOLD_EXPRESSIONS_REVISED
		LBAL_CPP_WARNING ("LBAL_CPP17_FOLD_EXPRESSIONS_REVISED is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_GUARANTEED_COPY_ELISION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_GUARANTEED_COPY_ELISION
		LBAL_CPP_WARNING ("LBAL_CPP17_GUARANTEED_COPY_ELISION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_HEX_FLOAT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_HEX_FLOAT
		LBAL_CPP_WARNING ("LBAL_CPP17_HEX_FLOAT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_INHERITING_CONSTRUCTORS_REVISED);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_INHERITING_CONSTRUCTORS_REVISED
		LBAL_CPP_WARNING ("LBAL_CPP17_INHERITING_CONSTRUCTORS_REVISED is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_INLINE_VARIABLES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_INLINE_VARIABLES
		LBAL_CPP_WARNING ("LBAL_CPP17_INLINE_VARIABLES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_NAMESPACE_ATTRIBUTES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_NAMESPACE_ATTRIBUTES
		LBAL_CPP_WARNING ("LBAL_CPP17_NAMESPACE_ATTRIBUTES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_NOEXCEPT_FUNCTION_TYPE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_NOEXCEPT_FUNCTION_TYPE
		LBAL_CPP_WARNING ("LBAL_CPP17_NOEXCEPT_FUNCTION_TYPE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_NONTYPE_TEMPLATE_ARGS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_NONTYPE_TEMPLATE_ARGS
		LBAL_CPP_WARNING ("LBAL_CPP17_NONTYPE_TEMPLATE_ARGS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_NONTYPE_TEMPLATE_PARAMETER_AUTO);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_NONTYPE_TEMPLATE_PARAMETER_AUTO
		LBAL_CPP_WARNING ("LBAL_CPP17_NONTYPE_TEMPLATE_PARAMETER_AUTO is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_RANGE_BASED_FOR_GENERALIZED);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_RANGE_BASED_FOR_GENERALIZED
		LBAL_CPP_WARNING ("LBAL_CPP17_RANGE_BASED_FOR_GENERALIZED is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_STATIC_ASSERT_NO_MESSAGE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_STATIC_ASSERT_NO_MESSAGE
		LBAL_CPP_WARNING ("LBAL_CPP17_STATIC_ASSERT_NO_MESSAGE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_STRUCTURED_BINDINGS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_STRUCTURED_BINDINGS
		LBAL_CPP_WARNING ("LBAL_CPP17_STRUCTURED_BINDINGS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_TEMPLATE_TEMPLATE_ARGS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_TEMPLATE_TEMPLATE_ARGS
		LBAL_CPP_WARNING ("LBAL_CPP17_TEMPLATE_TEMPLATE_ARGS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_VARIADIC_USING);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP17_VARIADIC_USING
		LBAL_CPP_WARNING ("LBAL_CPP17_VARIADIC_USING is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_AGGREGATE_PAREN_INIT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_AGGREGATE_PAREN_INIT
		LBAL_CPP_WARNING ("LBAL_CPP2A_AGGREGATE_PAREN_INIT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CHAR8_T);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CHAR8_T
		LBAL_CPP_WARNING ("LBAL_CPP2A_CHAR8_T is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_ALLOW_LAMBDA_CAPTURE_EQUALS_THIS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_ALLOW_LAMBDA_CAPTURE_EQUALS_THIS
		LBAL_CPP_WARNING ("LBAL_CPP2A_ALLOW_LAMBDA_CAPTURE_EQUALS_THIS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_ATTRIBUTE_LIKELY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_ATTRIBUTE_LIKELY
		LBAL_CPP_WARNING ("LBAL_CPP2A_ATTRIBUTE_LIKELY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_ATTRIBUTES_LIKELY_AND_UNLIKELY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_ATTRIBUTES_LIKELY_AND_UNLIKELY
		LBAL_CPP_WARNING ("LBAL_CPP2A_ATTRIBUTES_LIKELY_AND_UNLIKELY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_ATTRIBUTE_NO_UNIQUE_ADDRESS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_ATTRIBUTE_NO_UNIQUE_ADDRESS
		LBAL_CPP_WARNING ("LBAL_CPP2A_ATTRIBUTE_NO_UNIQUE_ADDRESS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_ATTRIBUTE_NODISCARD_EXPANDED);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_ATTRIBUTE_NODISCARD_EXPANDED
		LBAL_CPP_WARNING ("LBAL_CPP2A_ATTRIBUTE_NODISCARD_EXPANDED is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_ATTRIBUTE_UNLIKELY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_ATTRIBUTE_UNLIKELY
		LBAL_CPP_WARNING ("LBAL_CPP2A_ATTRIBUTE_UNLIKELY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONCEPTS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONCEPTS
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONCEPTS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONCEPTS_RESPECIFY_RETURN_TYPE_REQUIREMENTS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONCEPTS_RESPECIFY_RETURN_TYPE_REQUIREMENTS
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONCEPTS_RESPECIFY_RETURN_TYPE_REQUIREMENTS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONCEPTS_REFINE_RETURN_TYPE_REQUIREMENTS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONCEPTS_REFINE_RETURN_TYPE_REQUIREMENTS
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONCEPTS_REFINE_RETURN_TYPE_REQUIREMENTS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONDITIONAL_EXPLICIT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONDITIONAL_EXPLICIT
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONDITIONAL_EXPLICIT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONST_REF_QUALIFIED_POINTERS_TO_MEMBERS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONST_REF_QUALIFIED_POINTERS_TO_MEMBERS
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONST_REF_QUALIFIED_POINTERS_TO_MEMBERS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONSTEVAL);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONSTEVAL
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONSTEVAL is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONSTEXPR_DYNAMIC_ALLOC);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONSTEXPR_DYNAMIC_ALLOC
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONSTEXPR_DYNAMIC_ALLOC is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONSTEXPR_DYNAMIC_POLYMORPHISM);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONSTEXPR_DYNAMIC_POLYMORPHISM
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONSTEXPR_DYNAMIC_POLYMORPHISM is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONSTEXPR_IN_DECLTYPE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONSTEXPR_IN_DECLTYPE
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONSTEXPR_IN_DECLTYPE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONSTEXPR_INTRINSICS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONSTEXPR_INTRINSICS
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONSTEXPR_INTRINSICS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONSTEXPR_TRIVIAL_DEFAULT_INITIALIZATION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONSTEXPR_TRIVIAL_DEFAULT_INITIALIZATION
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONSTEXPR_TRIVIAL_DEFAULT_INITIALIZATION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONSTEXPR_TRY_CATCH);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONSTEXPR_TRY_CATCH
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONSTEXPR_TRY_CATCH is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONSTEXPR_UNION_ALTERATION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONSTEXPR_UNION_ALTERATION
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONSTEXPR_UNION_ALTERATION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONSTEXPR_VIRTUAL_FUNCTION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONSTEXPR_VIRTUAL_FUNCTION
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONSTEXPR_VIRTUAL_FUNCTION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_CONSTINIT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_CONSTINIT
		LBAL_CPP_WARNING ("LBAL_CPP2A_CONSTINIT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_COROUTINES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_COROUTINES
		LBAL_CPP_WARNING ("LBAL_CPP2A_COROUTINES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_DEDUCTION_GUIDES_FOR_AGGREGATES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_DEDUCTION_GUIDES_FOR_AGGREGATES
		LBAL_CPP_WARNING ("LBAL_CPP2A_DEDUCTION_GUIDES_FOR_AGGREGATES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_DEFAULT_CONSTRUCTIBLE_AND_ASSIGNABLE_STATELESS_LAMBDAS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_DEFAULT_CONSTRUCTIBLE_AND_ASSIGNABLE_STATELESS_LAMBDAS
		LBAL_CPP_WARNING ("LBAL_CPP2A_DEFAULT_CONSTRUCTIBLE_AND_ASSIGNABLE_STATELESS_LAMBDAS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_DEFAULT_MEMBER_INITIALIZERS_FOR_BIT_FIELDS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_DEFAULT_MEMBER_INITIALIZERS_FOR_BIT_FIELDS
		LBAL_CPP_WARNING ("LBAL_CPP2A_DEFAULT_MEMBER_INITIALIZERS_FOR_BIT_FIELDS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_DESIGNATED_INITIALIZERS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_DESIGNATED_INITIALIZERS
		LBAL_CPP_WARNING ("LBAL_CPP2A_DESIGNATED_INITIALIZERS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_DESTROYING_DELETE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_DESTROYING_DELETE
		LBAL_CPP_WARNING ("LBAL_CPP2A_DESTROYING_DELETE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_GENERIC_LAMBDAS_TEMPLATE_PARAMETER_LIST);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_GENERIC_LAMBDAS_TEMPLATE_PARAMETER_LIST
		LBAL_CPP_WARNING ("LBAL_CPP2A_GENERIC_LAMBDAS_TEMPLATE_PARAMETER_LIST is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_INIT_CAPTURES_PACK_EXPANSION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_INIT_CAPTURES_PACK_EXPANSION
		LBAL_CPP_WARNING ("LBAL_CPP2A_INIT_CAPTURES_PACK_EXPANSION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_INIT_STATEMENTS_FOR_RANGE_BASED_FOR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_INIT_STATEMENTS_FOR_RANGE_BASED_FOR
		LBAL_CPP_WARNING ("LBAL_CPP2A_INIT_STATEMENTS_FOR_RANGE_BASED_FOR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_INITIALIZER_LIST_CONSTRUCTORS_IN_CLASS_TEMPLATE_ARGUMENT_DEDUCTION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_INITIALIZER_LIST_CONSTRUCTORS_IN_CLASS_TEMPLATE_ARGUMENT_DEDUCTION
		LBAL_CPP_WARNING ("LBAL_CPP2A_INITIALIZER_LIST_CONSTRUCTORS_IN_CLASS_TEMPLATE_ARGUMENT_DEDUCTION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_INTEGRATING_OUR_FEATURE_TEST_MACROS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_INTEGRATING_OUR_FEATURE_TEST_MACROS
		LBAL_CPP_WARNING ("LBAL_CPP2A_INTEGRATING_OUR_FEATURE_TEST_MACROS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_MODULES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_MODULES
		LBAL_CPP_WARNING ("LBAL_CPP2A_MODULES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_NONTYPE_TEMPLATE_ARGS_FIXES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_NONTYPE_TEMPLATE_ARGS_FIXES
		LBAL_CPP_WARNING ("LBAL_CPP2A_NONTYPE_TEMPLATE_ARGS_FIXES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_NONTYPE_TEMPLATE_PARAMETER_CLASS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_NONTYPE_TEMPLATE_PARAMETER_CLASS
		LBAL_CPP_WARNING ("LBAL_CPP2A_NONTYPE_TEMPLATE_PARAMETER_CLASS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_THREE_WAY_COMPARISON_OPERATOR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_THREE_WAY_COMPARISON_OPERATOR
		LBAL_CPP_WARNING ("LBAL_CPP2A_THREE_WAY_COMPARISON_OPERATOR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_THREE_WAY_COMPARISON_OPERATOR_EQUALITY_FIX);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_THREE_WAY_COMPARISON_OPERATOR_EQUALITY_FIX
		LBAL_CPP_WARNING ("LBAL_CPP2A_THREE_WAY_COMPARISON_OPERATOR_EQUALITY_FIX is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_THREE_WAY_COMPARISON_OPERATOR_TUNEUP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_THREE_WAY_COMPARISON_OPERATOR_TUNEUP
		LBAL_CPP_WARNING ("LBAL_CPP2A_THREE_WAY_COMPARISON_OPERATOR_TUNEUP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_TYPENAME_OPTIONAL);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_TYPENAME_OPTIONAL
		LBAL_CPP_WARNING ("LBAL_CPP2A_TYPENAME_OPTIONAL is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_USING_ENUM);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_USING_ENUM
		LBAL_CPP_WARNING ("LBAL_CPP2A_USING_ENUM is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPP2A_VA_OPT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPP2A_VA_OPT
		LBAL_CPP_WARNING ("LBAL_CPP2A_VA_OPT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_C99_PREPROCESSOR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_C99_PREPROCESSOR
		LBAL_CPP_WARNING ("LBAL_C99_PREPROCESSOR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_CHRONO_UDLS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_CHRONO_UDLS
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_CHRONO_UDLS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_COMPLEX_UDLS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_COMPLEX_UDLS
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_COMPLEX_UDLS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_EXCHANGE_FUNCTION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_EXCHANGE_FUNCTION
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_EXCHANGE_FUNCTION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_GENERIC_ASSOCIATIVE_LOOKUP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_GENERIC_ASSOCIATIVE_LOOKUP
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_GENERIC_ASSOCIATIVE_LOOKUP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_INTEGER_SEQUENCE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_INTEGER_SEQUENCE
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_INTEGER_SEQUENCE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_INTEGRAL_CONSTANT_CALLABLE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_INTEGRAL_CONSTANT_CALLABLE
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_INTEGRAL_CONSTANT_CALLABLE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_IS_FINAL);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_IS_FINAL
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_IS_FINAL is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_IS_NULL_POINTER);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_IS_NULL_POINTER
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_IS_NULL_POINTER is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_MAKE_REVERSE_ITERATOR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_MAKE_REVERSE_ITERATOR
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_MAKE_REVERSE_ITERATOR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_MAKE_UNIQUE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_MAKE_UNIQUE
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_MAKE_UNIQUE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_NULL_ITERATORS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_NULL_ITERATORS
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_NULL_ITERATORS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_QUOTED_STRING_IO);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_QUOTED_STRING_IO
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_QUOTED_STRING_IO is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_RESULT_OF_SFINAE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_RESULT_OF_SFINAE
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_RESULT_OF_SFINAE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_ROBUST_NONMODIFYING_SEQ_OPS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_ROBUST_NONMODIFYING_SEQ_OPS
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_ROBUST_NONMODIFYING_SEQ_OPS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_SHARED_TIMED_MUTEX);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_SHARED_TIMED_MUTEX
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_SHARED_TIMED_MUTEX is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_STRING_UDLS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_STRING_UDLS
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_STRING_UDLS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_TRANSFORMATION_TRAIT_ALIASES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_TRANSFORMATION_TRAIT_ALIASES
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_TRANSFORMATION_TRAIT_ALIASES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_TRANSPARENT_OPERATORS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_TRANSPARENT_OPERATORS
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_TRANSPARENT_OPERATORS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_TUPLE_ELEMENT_T);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_TUPLE_ELEMENT_T
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_TUPLE_ELEMENT_T is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_TUPLES_BY_TYPE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP14_TUPLES_BY_TYPE
		LBAL_CPP_WARNING ("LBAL_LIBCPP14_TUPLES_BY_TYPE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ADDRESSOF_CONSTEXPR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_ADDRESSOF_CONSTEXPR
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_ADDRESSOF_CONSTEXPR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ALLOCATOR_TRAITS_IS_ALWAYS_EQUAL);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_ALLOCATOR_TRAITS_IS_ALWAYS_EQUAL
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_ALLOCATOR_TRAITS_IS_ALWAYS_EQUAL is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ANY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_ANY
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_ANY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ANY_INTERFACE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_ANY_INTERFACE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_ANY_INTERFACE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_APPLY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_APPLY
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_APPLY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ARRAY_CONSTEXPR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_ARRAY_CONSTEXPR
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_ARRAY_CONSTEXPR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_AS_CONST);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_AS_CONST
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_AS_CONST is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ATOMIC_IS_ALWAYS_LOCK_FREE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_ATOMIC_IS_ALWAYS_LOCK_FREE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_ATOMIC_IS_ALWAYS_LOCK_FREE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_BOOL_CONSTANT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_BOOL_CONSTANT
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_BOOL_CONSTANT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_BOYER_MOORE_SEARCHER);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_BOYER_MOORE_SEARCHER
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_BOYER_MOORE_SEARCHER is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_BYTE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_BYTE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_BYTE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_CHRONO);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_CHRONO
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_CHRONO is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_CHRONO_CONSTEXPR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_CHRONO_CONSTEXPR
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_CHRONO_CONSTEXPR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_CLAMP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_CLAMP
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_CLAMP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_EXECUTION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_EXECUTION
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_EXECUTION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ENABLE_SHARED_FROM_THIS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_ENABLE_SHARED_FROM_THIS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_ENABLE_SHARED_FROM_THIS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_FILESYSTEM);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_FILESYSTEM
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_FILESYSTEM is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_FILESYSTEM_PATHS_EXPANDED);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_FILESYSTEM_PATHS_EXPANDED
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_FILESYSTEM_PATHS_EXPANDED is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_FILESYSTEM_DIRECTORY_ENTRY_CACHING);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_FILESYSTEM_DIRECTORY_ENTRY_CACHING
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_FILESYSTEM_DIRECTORY_ENTRY_CACHING is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_FILESYSTEM_EXP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_FILESYSTEM_EXP
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_FILESYSTEM_EXP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_GCD_LCM);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_GCD_LCM
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_GCD_LCM is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_HARDWARE_INTERFERENCE_SIZE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_HARDWARE_INTERFERENCE_SIZE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_HARDWARE_INTERFERENCE_SIZE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_HAS_UNIQUE_OBJECT_REPRESENTATIONS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_HAS_UNIQUE_OBJECT_REPRESENTATIONS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_HAS_UNIQUE_OBJECT_REPRESENTATIONS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_HYPOT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_HYPOT
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_HYPOT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_INCOMPLETE_CONTAINER_ELEMENTS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_INCOMPLETE_CONTAINER_ELEMENTS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_INCOMPLETE_CONTAINER_ELEMENTS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_INVOKE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_INVOKE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_INVOKE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_IS_AGGREGATE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_IS_AGGREGATE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_IS_AGGREGATE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_IS_INVOCABLE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_IS_INVOCABLE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_IS_INVOCABLE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_IS_SWAPPABLE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_IS_SWAPPABLE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_IS_SWAPPABLE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_LAUNDER);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_LAUNDER
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_LAUNDER is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_LOGICAL_TRAITS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_LOGICAL_TRAITS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_LOGICAL_TRAITS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_MAKE_FROM_TUPLE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_MAKE_FROM_TUPLE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_MAKE_FROM_TUPLE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_MAP_TRY_EMPLACE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_MAP_TRY_EMPLACE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_MAP_TRY_EMPLACE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_MATH_SPECIAL_FUNCTIONS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_MATH_SPECIAL_FUNCTIONS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_MATH_SPECIAL_FUNCTIONS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_MEMORY_RESOURCE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_MEMORY_RESOURCE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_MEMORY_RESOURCE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_NODE_EXTRACT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_NODE_EXTRACT
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_NODE_EXTRACT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_NONMEMBER_CONTAINER_ACCESS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_NONMEMBER_CONTAINER_ACCESS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_NONMEMBER_CONTAINER_ACCESS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_NOT_FN);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_NOT_FN
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_NOT_FN is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_OPTIONAL);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_OPTIONAL
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_OPTIONAL is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_OPTIONAL_GREATER_EQUAL);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_OPTIONAL_GREATER_EQUAL
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_OPTIONAL_GREATER_EQUAL is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_OPTIONAL_INTERFACE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_OPTIONAL_INTERFACE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_OPTIONAL_INTERFACE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_PARALLEL_ALGORITHM);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_PARALLEL_ALGORITHM
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_PARALLEL_ALGORITHM is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_RAW_MEMORY_ALGORITHMS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_RAW_MEMORY_ALGORITHMS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_RAW_MEMORY_ALGORITHMS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_SAMPLE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_SAMPLE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_SAMPLE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_SCOPED_LOCK);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_SCOPED_LOCK
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_SCOPED_LOCK is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_SHARED_MUTEX);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_SHARED_MUTEX
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_SHARED_MUTEX is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_SHARED_PTR_ARRAYS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_SHARED_PTR_ARRAYS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_SHARED_PTR_ARRAYS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_SHARED_PTR_WEAK_TYPE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_SHARED_PTR_WEAK_TYPE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_SHARED_PTR_WEAK_TYPE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_STANDARDIZATION_OF_PARALLELISM_TS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_STANDARDIZATION_OF_PARALLELISM_TS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_STANDARDIZATION_OF_PARALLELISM_TS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_STRING_VIEW);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_STRING_VIEW
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_STRING_VIEW is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_STRING_VIEW_INTERFACE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_STRING_VIEW_INTERFACE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_STRING_VIEW_INTERFACE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_TO_CHARS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_TO_CHARS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_TO_CHARS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_TO_CHARS_FP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_TO_CHARS_FP
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_TO_CHARS_FP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_TO_CHARS_INTEGER);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_TO_CHARS_INTEGER
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_TO_CHARS_INTEGER is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_TRANSPARENT_OPERATORS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_TRANSPARENT_OPERATORS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_TRANSPARENT_OPERATORS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_TYPE_TRAIT_VARIABLE_TEMPLATES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_TYPE_TRAIT_VARIABLE_TEMPLATES
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_TYPE_TRAIT_VARIABLE_TEMPLATES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_UNCAUGHT_EXCEPTIONS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_UNCAUGHT_EXCEPTIONS
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_UNCAUGHT_EXCEPTIONS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_UNORDERED_MAP_TRY_EMPLACE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_UNORDERED_MAP_TRY_EMPLACE
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_UNORDERED_MAP_TRY_EMPLACE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_VARIANT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_VARIANT
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_VARIANT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_VOID_T);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP17_VOID_T
		LBAL_CPP_WARNING ("LBAL_LIBCPP17_VOID_T is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ARRAY_CONSTEXPR_ITERATOR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ARRAY_CONSTEXPR_ITERATOR
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ARRAY_CONSTEXPR_ITERATOR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ARRAY_CONSTEXPR_COMPARISONS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ARRAY_CONSTEXPR_COMPARISONS
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ARRAY_CONSTEXPR_COMPARISONS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ARRAY_CONSTEXPR_UTILITIES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ARRAY_CONSTEXPR_UTILITIES
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ARRAY_CONSTEXPR_UTILITIES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ASSUME_ALIGNED);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ASSUME_ALIGNED
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ASSUME_ALIGNED is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ATOMIC_FLAG_TEST);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ATOMIC_FLAG_TEST
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ATOMIC_FLAG_TEST is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ATOMIC_FLOAT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ATOMIC_FLOAT
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ATOMIC_FLOAT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ATOMIC_LOCK_FREE_TYPE_ALIASES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ATOMIC_LOCK_FREE_TYPE_ALIASES
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ATOMIC_LOCK_FREE_TYPE_ALIASES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ATOMIC_REF);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ATOMIC_REF
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ATOMIC_REF is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ATOMIC_SHARED_PTR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ATOMIC_SHARED_PTR
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ATOMIC_SHARED_PTR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ATOMIC_VALUE_INITIALIZATION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ATOMIC_VALUE_INITIALIZATION
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ATOMIC_VALUE_INITIALIZATION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ATOMIC_WAIT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ATOMIC_WAIT
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ATOMIC_WAIT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_BARRIER);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_BARRIER
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_BARRIER is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_BIND_FRONT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_BIND_FRONT
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_BIND_FRONT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_BIND_FRONT_NO_UNWRAP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_BIND_FRONT_NO_UNWRAP
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_BIND_FRONT_NO_UNWRAP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_BIT_CAST);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_BIT_CAST
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_BIT_CAST is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_BITOPS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_BITOPS
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_BITOPS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_BOUNDED_ARRAY_TRAITS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_BOUNDED_ARRAY_TRAITS
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_BOUNDED_ARRAY_TRAITS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CHAR8_T);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CHAR8_T
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CHAR8_T is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CHAR8_T_COMPAT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CHAR8_T_COMPAT
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CHAR8_T_COMPAT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CHRONO_CALENDAR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CHRONO_CALENDAR
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CHRONO_CALENDAR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CHRONO_FIXES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CHRONO_FIXES
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CHRONO_FIXES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONCEPTS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONCEPTS
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONCEPTS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONCEPTS_EXP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONCEPTS_EXP
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONCEPTS_EXP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONCEPTS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONCEPTS
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONCEPTS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONCEPTS_STANDARD_CASE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONCEPTS_STANDARD_CASE
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONCEPTS_STANDARD_CASE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_ALGORITHMS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_ALGORITHMS
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_ALGORITHMS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_ALGORITHMS_SWAP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_ALGORITHMS_SWAP
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_ALGORITHMS_SWAP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_ALGORITHMS_SWAP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_ALGORITHMS_SWAP
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_ALGORITHMS_SWAP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_DYNAMIC_ALLOC);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_DYNAMIC_ALLOC
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_DYNAMIC_ALLOC is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_FUNCTIONAL);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_FUNCTIONAL
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_FUNCTIONAL is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_FUNCTIONAL_INVOKE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_FUNCTIONAL_INVOKE
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_FUNCTIONAL_INVOKE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_ITERATOR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_ITERATOR
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_ITERATOR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_MEMORY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_MEMORY
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_MEMORY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_NUMERIC);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_NUMERIC
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_NUMERIC is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_STRING);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_STRING
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_STRING is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_STRING_VIEW);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_STRING_VIEW
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_STRING_VIEW is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_TUPLE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_TUPLE
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_TUPLE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_UTILITY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_UTILITY
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_UTILITY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_CONSTEXPR_VECTOR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_CONSTEXPR_VECTOR
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_CONSTEXPR_VECTOR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_COROUTINES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_COROUTINES
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_COROUTINES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_COROUTINES_EXP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_COROUTINES_EXP
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_COROUTINES_EXP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_DESTROYING_DELETE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_DESTROYING_DELETE
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_DESTROYING_DELETE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ENDIAN);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ENDIAN
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ENDIAN is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ENDIAN_BIT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ENDIAN_BIT
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ENDIAN_BIT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_ERASE_IF);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_ERASE_IF
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_ERASE_IF is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_FORMAT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_FORMAT
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_FORMAT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_GENERIC_UNORDERED_HASH_LOOKUP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_GENERIC_UNORDERED_HASH_LOOKUP
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_GENERIC_UNORDERED_HASH_LOOKUP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_GENERIC_UNORDERED_LOOKUP);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_GENERIC_UNORDERED_LOOKUP
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_GENERIC_UNORDERED_LOOKUP is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_INTERPOLATE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_INTERPOLATE
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_INTERPOLATE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_INT_POW2);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_INT_POW2
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_INT_POW2 is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_IS_CONSTANT_EVALUATED);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_IS_CONSTANT_EVALUATED
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_IS_CONSTANT_EVALUATED is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_IS_LAYOUT_COMPATIBLE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_IS_LAYOUT_COMPATIBLE
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_IS_LAYOUT_COMPATIBLE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_IS_POINTER_INTERCONVERTIBLE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_IS_POINTER_INTERCONVERTIBLE
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_IS_POINTER_INTERCONVERTIBLE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_JTHREAD);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_JTHREAD
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_JTHREAD is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_JTHREAD_CV);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_JTHREAD_CV
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_JTHREAD_CV is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_LATCH);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_LATCH
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_LATCH is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_LIST_REMOVE_RETURN_TYPE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_LIST_REMOVE_RETURN_TYPE
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_LIST_REMOVE_RETURN_TYPE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_MATH_CONSTANTS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_MATH_CONSTANTS
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_MATH_CONSTANTS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_MORE_CONSTEXPR_FOR_COMPLEX);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_MORE_CONSTEXPR_FOR_COMPLEX
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_MORE_CONSTEXPR_FOR_COMPLEX is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_NOTHROW_CONVERTIBLE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_NOTHROW_CONVERTIBLE
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_NOTHROW_CONVERTIBLE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_POLYMORPHIC_ALLOCATOR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_POLYMORPHIC_ALLOCATOR
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_POLYMORPHIC_ALLOCATOR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_RANGES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_RANGES
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_RANGES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_RANGES_INPUT_ADAPTORS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_RANGES_INPUT_ADAPTORS
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_RANGES_INPUT_ADAPTORS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_RANGES_LOOSENED_COMPARE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_RANGES_LOOSENED_COMPARE
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_RANGES_LOOSENED_COMPARE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_REMOVE_CVREF);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_REMOVE_CVREF
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_REMOVE_CVREF is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_SEMAPHORE);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_SEMAPHORE
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_SEMAPHORE is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_SHARED_PTR_ARRAYS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_SHARED_PTR_ARRAYS
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_SHARED_PTR_ARRAYS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_SHIFT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_SHIFT
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_SHIFT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_SMART_PTR_DEFAULT_INIT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_SMART_PTR_DEFAULT_INIT
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_SMART_PTR_DEFAULT_INIT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_SOURCE_LOCATION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_SOURCE_LOCATION
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_SOURCE_LOCATION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_SPAN);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_SPAN
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_SPAN is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_SPAN_USABILITY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_SPAN_USABILITY
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_SPAN_USABILITY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_STARTS_ENDS_WITH);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_STARTS_ENDS_WITH
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_STARTS_ENDS_WITH is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_STRING_VIEW_CONSTEXPR_ITERATOR);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_STRING_VIEW_CONSTEXPR_ITERATOR
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_STRING_VIEW_CONSTEXPR_ITERATOR is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_SYNCBUF);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_SYNCBUF
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_SYNCBUF is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_SYNCBUF_MANIPULATORS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_SYNCBUF_MANIPULATORS
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_SYNCBUF_MANIPULATORS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_THREE_WAY_COMPARISON);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_THREE_WAY_COMPARISON
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_THREE_WAY_COMPARISON is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_THREE_WAY_COMPARISON_LIBRARY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_THREE_WAY_COMPARISON_LIBRARY
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_THREE_WAY_COMPARISON_LIBRARY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_TO_ADDRESS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_TO_ADDRESS
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_TO_ADDRESS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_TO_ARRAY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_TO_ARRAY
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_TO_ARRAY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_TYPE_IDENTITY);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_TYPE_IDENTITY
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_TYPE_IDENTITY is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_UNWRAP_REF);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_UNWRAP_REF
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_UNWRAP_REF is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP2A_VERSION);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_LIBCPP2A_VERSION
		LBAL_CPP_WARNING ("LBAL_LIBCPP2A_VERSION is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPPTS_ATTRIBUTE_ASSERT);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPPTS_ATTRIBUTE_ASSERT
		LBAL_CPP_WARNING ("LBAL_CPPTS_ATTRIBUTE_ASSERT is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPPTS_ATTRIBUTE_ENSURES);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPPTS_ATTRIBUTE_ENSURES
		LBAL_CPP_WARNING ("LBAL_CPPTS_ATTRIBUTE_ENSURES is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPPTS_ATTRIBUTE_EXPECTS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPPTS_ATTRIBUTE_EXPECTS
		LBAL_CPP_WARNING ("LBAL_CPPTS_ATTRIBUTE_EXPECTS is UNSUPPORTED")
	#endif

	LBAL_DIAGNOSTIC_TEST(LBAL_CPPTS_CONTRACTS);
	#if LBAL_DIAGNOSTIC_COMPILE_TIME_REPORTING && !LBAL_CPPTS_CONTRACTS
		LBAL_CPP_WARNING ("LBAL_CPPTS_CONTRACTS is UNSUPPORTED")
	#endif

	EXPECT_TRUE (true);
}
