/*------------------------------------------------------------------------------

  Lucena Build Abstraction Library
  “lbalFeatureTest”
  Copyright © 2015-2026 Lucena
  All Rights Reserved

  This file is distributed under the University of Illinois Open Source
  License. See LICENSE.md for details.

------------------------------------------------------------------------------*/

//	lbal
#include <lucenaBAL/lucenaBAL.hpp>

//  gtest
#include <gtest/gtest.h>

//	std
#include <iostream>

/*------------------------------------------------------------------------------
  Declarations
*/

#define LBAL_DIAGNOSTIC_LOG_ALL_STATUS false
#define LBAL_DIAGNOSTIC_LOG_ALL_UNSUPPORTED true

#if LBAL_DIAGNOSTIC_LOG_ALL_STATUS
  #define LBAL_DIAGNOSTIC_LOG_SUPPORTED(LBAL_DIAGNOSTIC_feature_)              \
    std::cerr << LBAL_DIAGNOSTIC_feature_ " is supported" << std::endl;
#else
  #define LBAL_DIAGNOSTIC_LOG_SUPPORTED(LBAL_DIAGNOSTIC_feature_)
#endif

#if LBAL_DIAGNOSTIC_LOG_ALL_STATUS || LBAL_DIAGNOSTIC_LOG_ALL_UNSUPPORTED
  #define LBAL_DIAGNOSTIC_LOG_UNSUPPORTED(LBAL_DIAGNOSTIC_feature_)            \
    std::cerr << LBAL_DIAGNOSTIC_feature_ " is UNSUPPORTED" << std::endl;
#elif
  #define LBAL_DIAGNOSTIC_LOG_UNSUPPORTED(LBAL_DIAGNOSTIC_feature_)
#endif

#if LBAL_CPP17_IF_CONSTEXPR
  #define LBAL_IF_CONSTEXPR if constexpr
#else
  #define LBAL_IF_CONSTEXPR if
#endif

#define LBAL_DIAGNOSTIC_TEST(LBAL_DIAGNOSTIC_feature_)                         \
  do {                                                                         \
    LBAL_IF_CONSTEXPR (0 == LBAL_DIAGNOSTIC_feature_) {                        \
      LBAL_DIAGNOSTIC_LOG_UNSUPPORTED(#LBAL_DIAGNOSTIC_feature_)               \
    } else {                                                                   \
      LBAL_DIAGNOSTIC_LOG_SUPPORTED(#LBAL_DIAGNOSTIC_feature_)                 \
    }                                                                          \
  } while (false)

using namespace LBAL_;

/*------------------------------------------------------------------------------
 */

GTEST_TEST(lbalTest, Validation) {
  /*
    Report the results of the various feature tests; depending on your IDE, you
    may not even need to explicitly compile to see the test results.
  */

  // C++03

  LBAL_DIAGNOSTIC_TEST(LBAL_CPP03_EXCEPTIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP03_RTTI);

  // C++11

  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_ALIAS_TEMPLATES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_ATTRIBUTES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_ATTRIBUTE_CARRIES_DEPENDENCY);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_ATTRIBUTE_NORETURN);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_CONSTEXPR);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_DECLTYPE);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_DELEGATING_CONSTRUCTORS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_INHERITING_CONSTRUCTORS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_INITIALIZER_LISTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_LAMBDAS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_MINIMAL_GARBAGE_COLLECTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_NSDMI);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_RANGE_BASED_FOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_RAW_STRINGS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_REF_QUALIFIERS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_RVALUE_REFERENCES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_STATIC_ASSERT);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_THREADSAFE_STATIC_INIT);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_UNICODE_CHARACTERS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_UNICODE_LITERALS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_USER_DEFINED_LITERALS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP11_VARIADIC_TEMPLATES);

  // C++14

  LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_AGGREGATE_NSDMI);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_ATTRIBUTE_DEPRECATED);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_BINARY_LITERALS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_CONSTEXPR_RELAXED_CONSTRAINTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_DECLTYPE_AUTO);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_GENERIC_LAMBDAS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_INIT_CAPTURES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_RETURN_TYPE_DEDUCTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_SIZED_DEALLOCATION);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP14_VARIABLE_TEMPLATES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_CHRONO_UDLS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_COMPLEX_UDLS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_EXCHANGE_FUNCTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_GENERIC_ASSOCIATIVE_LOOKUP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_INTEGER_SEQUENCE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_INTEGRAL_CONSTANT_CALLABLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_IS_FINAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_IS_NULL_POINTER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_MAKE_REVERSE_ITERATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_MAKE_UNIQUE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_NULL_ITERATORS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_QUOTED_STRING_IO);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_RESULT_OF_SFINAE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_ROBUST_NONMODIFYING_SEQ_OPS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_SHARED_TIMED_MUTEX);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_STRING_UDLS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_TRANSFORMATION_TRAIT_ALIASES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_TRANSPARENT_OPERATORS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_TUPLES_BY_TYPE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP14_TUPLE_ELEMENT_T);

  // C++17

  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_AGGREGATE_BASES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_ALIGNED_NEW);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_ATTRIBUTE_FALLTHROUGH);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_ATTRIBUTE_MAYBE_UNUSED);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_ATTRIBUTE_NODISCARD);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_CAPTURE_STAR_THIS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_CONSTEXPR_LAMBDA);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_DEDUCTION_GUIDES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_DEDUCTION_GUIDES_DR);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_DEDUCTION_GUIDES_NB);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_ENUMERATOR_ATTRIBUTES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_FOLD_EXPRESSIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_FOLD_EXPRESSIONS_REVISED);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_GUARANTEED_COPY_ELISION);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_HEX_FLOAT);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_IF_CONSTEXPR);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_INHERITING_CONSTRUCTORS_REVISED);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_INLINE_VARIABLES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_NAMESPACE_ATTRIBUTES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_NOEXCEPT_FUNCTION_TYPE);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_NONTYPE_TEMPLATE_ARGS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_NONTYPE_TEMPLATE_PARAMETER_AUTO);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_RANGE_BASED_FOR_GENERALIZED);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_STATIC_ASSERT_NO_MESSAGE);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_STRUCTURED_BINDINGS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_TEMPLATE_TEMPLATE_ARGS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP17_VARIADIC_USING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ADDRESSOF_CONSTEXPR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ALLOCATOR_TRAITS_IS_ALWAYS_EQUAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ANY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ANY_INTERFACE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_APPLY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ARRAY_CONSTEXPR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_AS_CONST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ATOMIC_IS_ALWAYS_LOCK_FREE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_BOOL_CONSTANT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_BOYER_MOORE_SEARCHER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_BYTE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_CHRONO);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_CHRONO_CONSTEXPR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_CLAMP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_CONSTEXPR_STRING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_CONSTEXPR_STRING_VIEW);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_DEDUCTION_GUIDES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_ENABLE_SHARED_FROM_THIS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_EXECUTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_FILESYSTEM);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_FILESYSTEM_DIRECTORY_ENTRY_CACHING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_FILESYSTEM_EXP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_FILESYSTEM_PATHS_EXPANDED);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_FILESYSTEM_RELATIVE_PATHS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_GCD_LCM);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_HARDWARE_INTERFERENCE_SIZE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_HAS_UNIQUE_OBJECT_REPRESENTATIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_HYPOT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_INCOMPLETE_CONTAINER_ELEMENTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_INVOKE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_IS_AGGREGATE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_IS_INVOCABLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_IS_SWAPPABLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_LAUNDER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_LOGICAL_TRAITS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_MAKE_FROM_TUPLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_MAP_TRY_EMPLACE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_MATH_SPECIAL_FUNCTIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_MEMORY_RESOURCE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_NODE_EXTRACT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_NONMEMBER_CONTAINER_ACCESS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_NOT_FN);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_OPTIONAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_OPTIONAL_GREATER_EQUAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_OPTIONAL_INTERFACE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_PARALLEL_ALGORITHM);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_RAW_MEMORY_ALGORITHMS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_SAMPLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_SCOPED_LOCK);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_SHARED_MUTEX);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_SHARED_PTR_ARRAYS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_SHARED_PTR_WEAK_TYPE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_STANDARDIZATION_OF_PARALLELISM_TS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_STRING_VIEW);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_STRING_VIEW_INTERFACE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_TO_CHARS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_TO_CHARS_FP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_TO_CHARS_INTEGER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_TRANSPARENT_OPERATORS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_TYPE_TRAIT_VARIABLE_TEMPLATES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_UNCAUGHT_EXCEPTIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_UNORDERED_MAP_TRY_EMPLACE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_VARIANT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP17_VOID_T);

  // C++20

  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_AGGREGATE_PAREN_INIT);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_ALLOW_LAMBDA_CAPTURE_EQUALS_THIS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_ATTRIBUTES_LIKELY_AND_UNLIKELY);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_ATTRIBUTE_LIKELY);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_ATTRIBUTE_NODISCARD_EXPANDED);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_ATTRIBUTE_NO_UNIQUE_ADDRESS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_ATTRIBUTE_UNLIKELY);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CHAR8_T);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONCEPTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONCEPTS_CONDITIONALLY_TRIVIAL_SPECIAL_MEMBER_FUNCTIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONCEPTS_REFINE_RETURN_TYPE_REQUIREMENTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONCEPTS_RESPECIFY_RETURN_TYPE_REQUIREMENTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONDITIONAL_EXPLICIT);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONSTEVAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONSTEXPR_CHANGE_ACTIVE_UNION_MEMBER);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONSTEXPR_DYNAMIC_ALLOC);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONSTEXPR_DYNAMIC_POLYMORPHISM);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONSTEXPR_INTRINSICS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONSTEXPR_IN_DECLTYPE);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONSTEXPR_TRIVIAL_DEFAULT_INITIALIZATION);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONSTEXPR_TRY_CATCH);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONSTEXPR_UNION_ALTERATION);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONSTEXPR_VIRTUAL_FUNCTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONSTINIT);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_CONST_REF_QUALIFIED_POINTERS_TO_MEMBERS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_DEDUCTION_GUIDES_FOR_AGGREGATES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_DEFAULT_CONSTRUCTIBLE_AND_ASSIGNABLE_STATELESS_LAMBDAS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_DEFAULT_MEMBER_INITIALIZERS_FOR_BIT_FIELDS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_DESIGNATED_INITIALIZERS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_DESTROYING_DELETE);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_GENERIC_LAMBDAS_TEMPLATE_PARAMETER_LIST);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_IMPL_COROUTINE);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_INIT_CAPTURES_PACK_EXPANSION);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_INIT_STATEMENTS_FOR_RANGE_BASED_FOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_INTEGRATING_OUR_FEATURE_TEST_MACROS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_MODULES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_NONTYPE_TEMPLATE_ARGS_FIXES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_NONTYPE_TEMPLATE_PARAMETER_CLASS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_THREE_WAY_COMPARISON_OPERATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_THREE_WAY_COMPARISON_OPERATOR_EQUALITY_FIX);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_THREE_WAY_COMPARISON_OPERATOR_TUNEUP);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_TYPENAME_OPTIONAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_USING_ENUM);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP20_VA_OPT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ARRAY_CONSTEXPR_COMPARISONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ARRAY_CONSTEXPR_ITERATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ARRAY_CONSTEXPR_UTILITIES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ASSUME_ALIGNED);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ATOMIC_FLAG_TEST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ATOMIC_FLOAT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ATOMIC_LOCK_FREE_TYPE_ALIASES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ATOMIC_REF);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ATOMIC_SHARED_PTR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ATOMIC_VALUE_INITIALIZATION);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ATOMIC_WAIT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_BARRIER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_BIND_FRONT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_BIND_FRONT_NO_UNWRAP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_BITOPS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_BIT_CAST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_BOUNDED_ARRAY_TRAITS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CHAR8_T);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CHAR8_T_COMPAT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CHRONO_CALENDAR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CHRONO_FIXES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONCEPTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONCEPTS_BOOLEAN_TESTABLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONCEPTS_EXP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONCEPTS_STANDARD_CASE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_ALGORITHMS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_ALGORITHMS_SWAP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_COMPLEX);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_DYNAMIC_ALLOC);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_FUNCTIONAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_FUNCTIONAL_INVOKE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_ITERATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_MEMORY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_NUMERIC);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_STRING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_STRING_PARTIAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_STRING_VIEW);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_TUPLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_UTILITY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_CONSTEXPR_VECTOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_COROUTINE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_COROUTINE_EXP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_DESTROYING_DELETE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ENDIAN);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ENDIAN_BIT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ERASE_IF);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_ERASE_IF_FREE_FUNCTIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_EXECUTION_VECTORIZATION);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_FORMAT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_GENERIC_UNORDERED_HASH_LOOKUP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_GENERIC_UNORDERED_LOOKUP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_INTEGER_COMPARISON_FUNCTIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_INTERPOLATE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_INT_POW2);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_INT_POW2_FUNCTION_RENAME);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_IS_CONSTANT_EVALUATED);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_IS_LAYOUT_COMPATIBLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_IS_NOTHROW_CONVERTIBLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_IS_POINTER_INTERCONVERTIBLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_JTHREAD);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_JTHREAD_CV);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_LATCH);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_LIST_REMOVE_RETURN_TYPE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_MATH_CONSTANTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_POLYMORPHIC_ALLOCATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_RANGES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_RANGES_INPUT_ADAPTORS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_RANGES_LOOSENED_COMPARE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_REMOVE_CVREF);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_SEMAPHORE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_SHARED_PTR_ARRAYS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_SHIFT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_SMART_PTR_FOR_OVERWRITE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_SOURCE_LOCATION);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_SPAN);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_SPAN_FIXED_SIZE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_SPAN_USABILITY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_SSIZE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_STARTS_ENDS_WITH);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_STRING_VIEW_CONSTEXPR_ITERATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_SYNCBUF);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_SYNCBUF_MANIPULATORS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_THREE_WAY_COMPARISON);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_THREE_WAY_COMPARISON_LIBRARY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_TO_ADDRESS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_TO_ARRAY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_TYPE_IDENTITY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_UNWRAP_REF);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP20_VERSION);

  // C++23

  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_ATTRIBUTE_ASSUME);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_AUTO_CAST);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_CHAR8_T_COMPATIBILITY);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_CONSTEVAL_PROPAGATE_UP);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_CONSTEXPR_NON_LITERAL_VARIABLES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_CONSTEXPR_PERMIT_STATIC_CONSTEXPR);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_CONSTEXPR_RELAX_RESTRICTIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_DEDUCTION_GUIDES_FROM_INHERITED_CONSTRUCTORS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_EXPLICIT_THIS_PARAMETER);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_IF_CONSTEVAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_IMPLICIT_MOVE);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_MULTIDIMENSIONAL_SUBSCRIPT);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_MULTIDIMENSIONAL_SUBSCRIPT_STATIC);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_NAMED_CHARACTER_ESCAPES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_RANGE_BASED_FOR_TEMPORARIES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_SIZE_T_SUFFIX);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP23_STATIC_CALL_OPERATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_ADAPTOR_ITERATOR_PAIR_CONSTRUCTOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_ALGORITHM_ITERATOR_REQUIREMENTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_ALLOCATE_AT_LEAST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_ALLOCATE_AT_LEAST_DISALLOW_USER_SPEC);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_ASSOCIATIVE_HETEROGENEOUS_ERASURE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_BARRIER_RELAXED_COMPLETION);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_BIND_BACK);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_BYTESWAP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_COMMON_REFERENCE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_COMMON_REFERENCE_WRAPPER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_CONCEPTS_MOVE_ONLY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_CONSTEXPR_BITSET);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_CONSTEXPR_CHARCONV);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_CONSTEXPR_CMATH);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_CONSTEXPR_MEMORY_UNIQUE_PTR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_CONSTEXPR_TYPEINFO);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_CONTAINERS_RANGES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_EXPECTED);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_EXPECTED_MONADIC);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_FLAT_MAP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_FLAT_SET);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_FORMAT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_FORMATTERS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_FORMAT_BASIC_FORMAT_STRING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_FORMAT_ENCODINGS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_FORMAT_GENERATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_FORMAT_LOCALE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_FORMAT_RANGES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_FORWARD_LIKE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_GENERATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_INVOKE_R);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_IOS_NOREPLACE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_IS_IMPLICIT_LIFETIME);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_IS_SCOPED_ENUM);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_MDSPAN);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_MODULES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_MOVE_ITERATOR_CONCEPT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_MOVE_ONLY_FUNCTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_OPTIONAL_CONSTEXPR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_OPTIONAL_MONADIC);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_OUT_PTR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_PRINT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_AS_CONST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_AS_RVALUE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_CARTESIAN_PRODUCT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_CARTESIAN_PRODUCT_EMPTY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_CHUNK);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_CHUNK_BY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_CONTAINS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_ENUMERATE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_FIND_LAST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_FOLD);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_FORMALIZED_VIEW);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_IOTA);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_JOIN_WITH);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_NON_DEFAULT_CONSTRUCTIBLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_RELAXED);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_REMOVE_POISON_PILLS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_REPEAT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_SLIDE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_STARTS_ENDS_WITH);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_STRIDE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_SUPPORT_MOVE_ONLY_TYPES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_TO_CONTAINER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_USER_ADAPTOR_PIPES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_RANGES_ZIP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_REFERENCE_FROM_TEMPORARY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_SHIFT_RANGES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_SPANSTREAM);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_STACKTRACE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_START_LIFETIME_AS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_STDATOMIC_H);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_STRING_CONTAINS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_STRING_RESIZE_AND_OVERWRITE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_TO_UNDERLYING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_TUPLE_LIKE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_UNREACHABLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_VARIANT_CONSTEXPR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP23_VARIANT_INHERITANCE);

  // C++26

  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_CONSTEXPR_CAST_FROM_VOID_STAR);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_CONSTEXPR_EXCEPTIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_CONSTEXPR_PLACEMENT_NEW);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_CONSTEXPR_VIRTUAL_INHERITANCE);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_CONTRACTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_DELETED_FUNCTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_EXPANSION_STATEMENTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_IMPL_REFLECTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_PACK_INDEXING);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_PLACEHOLDER_VARIABLES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_STATIC_ASSERT_USER_MESSAGE);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_STRUCTURED_BINDINGS_ATTRIBUTES);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_STRUCTURED_BINDINGS_PACK);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_TEMPLATE_PARAMETERS);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_TRIVIAL_UNION);
  LBAL_DIAGNOSTIC_TEST(LBAL_CPP26_VARIADIC_FRIEND);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_ALIGNED_ACCESSOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_ASSOCIATIVE_HETEROGENEOUS_INSERTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_ATOMIC_MIN_MAX);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_ATOMIC_MIN_MAX_FLOAT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_ATOMIC_REDUCTIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_ATOMIC_REF_ADDRESS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_BIND_FRONT_NTTP_CALLABLES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_BITSET);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CHRONO_HASHING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTANT_WRAPPER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_ALGORITHMS_STABLE_SORT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_ATOMIC);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_COMPLEX);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_DEQUE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_EXCEPTIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_FLAT_MAP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_FLAT_SET);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_FORMAT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_FORWARD_LIST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_LIST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_MAP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_MEMORY_SHARED_PTR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_QUEUE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_SET);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_STACK);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_UNORDERED_MAP);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTEXPR_UNORDERED_SET);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTRAINED_EQUALITY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_CONSTRAINED_EQUALITY_EXPECTED);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_COPYABLE_FUNCTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_COUNTING_SCOPE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_DEBUGGING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_DEBUGGING_UTILITIES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_DEFAULT_TEMPLATE_TYPE_FOR_ALGORITHM_VALUES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_DEFINE_STATIC);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_EXCEPTION_PTR_CAST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_EXCEPTION_PTR_CAST_CONSTEXPR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FLAT_MAP_FIXES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FLAT_SET_FIXES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FORMAT_MEMBER_VISIT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FORMAT_PATH);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FORMAT_PATH_FIXES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FORMAT_POINTERS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FORMAT_RUNTIME);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FORMAT_TYPE_CHECK);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FORMAT_UCHAR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_ALGORITHM);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_ALGORITHM_MORE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_ARRAY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_CHARCONV);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_CHAR_TRAITS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_CSTDLIB);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_CSTRING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_CSTRING_REMOVE_STRTOK);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_CWCHAR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_ERRC);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_EXECUTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_EXPECTED);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_FEATURE_TEST_MACROS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_FUNCTIONAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_ITERATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_MDSPAN);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_MEMORY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_MEMORY_MORE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_NUMERIC);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_OPERATOR_NEW);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_OPTIONAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_RANDOM);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_RANGES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_RATIO);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_STRING_VIEW);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_TUPLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_UTILITY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FREESTANDING_VARIANT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FSTREAM_NATIVE_HANDLE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FUNCTION_REF);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_FUNCTION_REF_RENAME_NONTYPE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_GENERATE_RANDOM);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_ARRAY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_BASIC_STACKTRACE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_BASIC_STRING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_BASIC_STRING_VIEW);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_BITSET);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_COMMON_ITERATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_COUNTED_ITERATOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_DEQUE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_EXPECTED);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_FORWARD_LIST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_INPLACE_VECTOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_LIST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_MDSPAN);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_OPTIONAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_SHARED_PTR_ARRAY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_SPAN);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_VALARRAY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_VECTOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HARDENED_VIEW_INTERFACE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HAZARD_POINTER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_HIVE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_INDIRECT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_INITIALIZER_LIST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_INPLACE_VECTOR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_INTEGER_SEQUENCE_EXPANSION_STATEMENTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_IS_VIRTUAL_BASE_OF);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_IS_WITHIN_LIFETIME);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_LINALG);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_LINALG_BLAS_RANK);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_LINALG_FIX_TRANSPOSED);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_LINALG_OPTIMIZE_CONJUGATED);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_MDSPAN_DEXTENTS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_NOT_FN_NTTP_CALLABLES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_OBSERVABLE_CHECKPOINT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_OPTIONAL_RANGE_SUPPORT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_OPTIONAL_REFERENCE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_OUT_PTR_MORE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_PARALLEL_ALGORITHM_RANGE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_PARALLEL_SCHEDULER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_PHILOX_ENGINE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_POLYMORPHIC);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_PRINT_EFFICIENT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_PRINT_MORE_EFFICIENT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_RANGES_AS_CONST_FIX_CONVERTIBILITY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_RANGES_CACHE_LATEST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_RANGES_CONCAT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_RANGES_INDICES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_RANGES_REMOVE_COMMON_REF_REQ);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_RANGES_RESERVE_HINT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_RANGES_TO_INPUT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_RATIO);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_RAW_MEMORY_ALGORITHMS_CONSTEXPR);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_RCU);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_REFERENCE_WRAPPER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_REFLECTION);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SATURATION_ARITHMETIC);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SENDERS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SENDERS_OPTIONAL);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SIMD);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SIMD_BIT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SIMD_CHUNK);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SIMD_COMPLEX);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SIMD_DEDUCTION_GUIDES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SIMD_EXTEND);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SIMD_NAMESPACES);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SIMD_PERMUTATIONS);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SIMD_RANGE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SMART_POINTER_OWNER_EQUALITY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SMART_PTR_OWNER_EQUALITY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SPAN_AT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SPAN_INITIALIZER_LIST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SPAN_MORE);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SSTREAM_FROM_STRING_VIEW);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_STRING_SUBVIEW);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_STRING_VIEW_CONCAT);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SUBMDSPAN);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SUBMDSPAN_FIX);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SUBMDSPAN_FUTURE_PROOF);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_SUBMDSPAN_PADDED);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_TASK);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_TEXT_ENCODING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_TO_CHARS_BOOL_TEST);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_TO_STRING);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_TUPLE_LIKE_COMPLEX);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_TYPE_ORDER);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_VALARRAY);
  LBAL_DIAGNOSTIC_TEST(LBAL_LIBCPP26_VARIANT_VISITOR);

  EXPECT_TRUE(true);
}

#undef LBAL_IF_CONSTEXPR
