---
# Lucena Build Abstraction Library
# “main.yml”
# Copyright © 2026 Lucena
# All Rights Reserved
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.md for details.
#
# Update Doxygen-generated docs whenever we commit to `main`.

name: Doxygen gh-pages Update Action

# on:
#   push:
#     branches:
#       - main

# Temp for testing
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
        with:
          # Use a shallow clone to keep Doxygen focused.
          fetch-depth: 0
          submodules: "true"

      - name: Install dependencies
        # `noble` only includes `doxygen-1.9.x`; we install a newer version 
        # below.
        run: sudo apt update && sudo apt install -y graphviz wget
        shell: bash

      - name: Install Doxygen
        run: |
          doxygen_version='1.17.0'
          doxygen_dir_version="$(tr '.' '_' <<< "${doxygen_version}")"

          temp_dir="$(mktemp -d "doxygen.XXXXXX")"
          trap 'rm -rf "${temp_dir}"' EXIT

          # FIXME Possible supply-chain attack vector; archive should be cached 
          # in a safe location. Even just adding a hash check would be better.
          pushd "${temp_dir}" >/dev/null || exit 31
            wget "https://github.com/doxygen/doxygen/releases/download/Release_${doxygen_dir_version}/doxygen-${doxygen_version}.linux.bin.tar.gz" \
            || exit 32

            tar xf "doxygen-${doxygen_version}.linux.bin.tar.gz" \
            || exit 33

            mkdir -p "/usr/local/bin" \
            || exit 34

            sudo mv \
              "doxygen-${doxygen_version}/bin/doxygen" \
              "/usr/local/bin/doxygen" \
            || exit 35
          popd >/dev/null
        shell: bash

      - name: Generate docs
        env:
          CC: "gcc-15"
          CXX: "g++-15"

        # We run a full CMake build for this as some input files are 
        # dynamically generated.
        run: |
          mkdir -p build > /dev/null \
          || exit 41

          cmake -S . -B build -DCMAKE_BULD_TYPE=Release -DLBAL_BUILD_DOCS=ON \
          || exit 42

          cmake --build build \
          || exit 43

          # Prevent `jekyll` from causing trouble, if it runs.
          touch "build/docs/doxygen/html/.nojekyll" \
          || exit 44

          # Top-level redirect
          cp -n \
            "docs/index.html" \
            "build/docs/doxygen/index.html" \
          || exit 45
        shell: bash

      - name: Doxygen
        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # FIXME - Another supply-chain attack vector; in this case, replicating
      # the functionality may be the best option.
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "build/docs/doxygen"
          token: ${{ secrets.GITHUB_TOKEN }}

...
